## Save configuration to TFTP

---
- hosts: dellos6_switch1
  connection: network_cli
  gather_facts: no

  vars:
   - ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - /etc/ansible/group_vars/dellos

  tasks:
  - name: "Save running configuration to TFTP."
    dellos6_config:
      commands:  
        - command: 'do copy running-config tftp://172.16.100.100/192.168.1.100'
          prompt: '\(y/n\)\s?$'
          answer: "y"
    register: handle_prompt

